# Trac-specific information
trac:
  # Trac database location
  database: sqlite://db/trac.db
  # database: mysql2://user:password@host:port/database
  # database: mysql2://root:password@mysql:3306/foobar

  # URL of the Trac "tickets" interface
  ticketbaseurl: https://example.org/trac/foobar/ticket

# GitHub-specific information
github:
  # Target GitHub organization and repo name
  repo: 'example-org/target-repository'

  # GitHub user Personal Access Token
  token: 'ghp_fpsc4de1f0c46e01576810740c9242097cba4619486'

# RevMap file to use for migration
revmap_path: ./example-revmap.txt

# User map: Trac username to GitHub username
# - Please ensure the GitHub usernames are correct and valid, otherwise
#   the issue migration process will fail if the GitHub user specified as owner
#   (assignee) does not exist.
users:
  # email: <Trac email or username>
  # name: <Name of the person (optional)>
  # username: <username on GitHub>
  - email: matthew@example.org
    name: Matthew
    username: example-matt

  - email: valencia
    name: Valencia
    username: example-vale

# Label mapping from Trac ticket to GitHub label
labels:
  type:
    Feature Request:    feature request
    Defect:             defect
    Task:               task
  component:
    configuration:      conf
    documentation:      doc
  resolution:
    Invalid:            invalid
    Duplicate:          duplicate
    Wontfix:            wontfix
  platform:
    Linux:              Linux
    Windows:            Windows

  # less useful, but also possible:
  priority:
    Low:
      name:             low
      color:            22dd00
    High:
      name:             high
      color:            ff0000
  severity:
    trivial:
      name:             trivial
      color:            ff0000
    major:
      name:             major
      color:            b44647
    minor:
      name:             minor
      color:            f7347a
    medium:
      name:             medium
      color:            f3c77c
  tracstate:
    accepted:
      name:             accepted
      color:            22dd00
    assigned:
      name:             assigned
      color:            aadd88
    closed:
      name:             closed
      color:            ee00aa
    new:
      name:             new
      color:
  version:
    '1.3':              v1.3
    '1.4':              v1.4

milestones:
  '2021_02':
    name: '2021_02'
    due: 1392595200000000
    completed: 1415959156000000
    description: ''

attachments:
  url: "https://github.com/example-org/raw/main/from_tractive"
  # export-folder is relative to export-script
  export_folder: "./attachments"
  export_script: ./attachments.sh
