trac:
  database: sqlite://db/trac.db
  # database: mysql2://user:password@host:port/database
  # database: mysql2://root:password@mysql:3306/foobar
  ticketbaseurl: https://foo.bar/trac/foobar/ticket

github:
  repo: 'tractive/test'
  token: '49b1c8d34401abc06040cf64bf9a8bfed5f30ca9'
  local_repo_path: '/Users/user/repo-git'

revmapfile: ../foobar-revmap.txt
rev_timestamp_file: ./revtimestamp.fo
revmap_output_file: revmap.txt

# make sure not to typo the GitHub username as the issue will fail to create if a ticket's
# owner (assignee) has a valid mapping below and that user does not exist in github
users:
  # <email/username>: <username on github>
  matthias@tractive.com: matthias
  vallenti: tractive

labels:
  type:
    Feature Request:    feature request
    Defect:             defect
    Task:               task
  component:
    configuration:      conf
    documentation:      doc
  resolution:
    Invalid:            invalid
    Duplicate:          duplicate
    Wontfix:            wontfix
  platform:
    Linux:              Linux
    Windows:            Windows

  # less useful, but also possible:
  priority:
    Low:                '@low'
    High:               '@high'
  severity:
    blocker:            '#high'
    critical:           '#critical'
    major:              '#major'
    minor:              '#minor'
    trivial:            '#trivial'
  version:
    '1.3':              v1.3
    '1.4':              v1.4

milestones:
  '2014_02':
    :name: '2014_02'
    :due: 1392595200000000
    :completed: 1415959156000000
    :description: ''

attachments:
  url: "https://github.com/foobar/raw/develop/from_tractive"
  # export-folder is relative to export-script
  export_folder: "./attachments"
  export_script: ./attachments.sh

