= Tractive: migrating from Trac to GitHub

== Purpose

Tractive is a tool that helps you migrate Trac instances to GitHub.

Specifically, it converts http://trac.edgewall.org[Trac] tickets into
https://github.com/[GitHub] Issues by accessing the Trac database's issues and posts the change
history of each ticket as comments.

Tractive is written using re-tooled code based on the
https://github.com/mavam/trac-hub[trac-hub] migration tool which is excellent.

NOTE: This tool was created in order to perform Trac-to-GitHub migration
for the https://www.ietf.org/[IETF].

== Installation

Install it via:

[source,sh]
----
$ gem install tractive
----

== Usage

==== Prerequisites

2.  https://git-scm.com/book/en/v2/Getting-Started-Installing-Git[Git]
3.  A https://github.com/[GitHub] Account

==== How to use it

1.  Install `Tractive`:

        gem install tractive

2.  Validate the config file.
3.  Run Tractive:

        tractive <options>

=== Command Line Options

|===
|         **Option**          |   **Description**                                                                         |  **Type**
|  -A, --attachment-exporter  |      Generate an attachment exporter script according to config.yaml.                     |   String
|  -a, --attachment-url       |      Add URL to Cloud Host where attachment files are available.                          |   String
|  -c                         |      Set the configuration file. Default: `tractive.config.yaml`.                         |   String
|  -d, --dry-run              |      Write data to a file instead of pushing it to Github.                                |   Boolean
|  -e, --export-attachments   |      Export attachments from the database according to config.yaml.                       |   String
|  -F, --fast-import          |      Import without safety-checking issue numbers.                                        |   Boolean
|  -f, --filter               |      Filter records that you want to import. Options of `column-name`, `operator` and `column-value` are required for filtering.|   Boolean
|  --column-name              |      Name of the column to filter.                                                        |   String
|  --operator                 |      Operator for filter. Example of operators include `LIKE` and `=`.                    |   String
|  --column-value             |      Value of the column to filter.                                                       |   String
|  -G, --generate-revmap      |      Generate a mapping from svn revision number to git sha hash. The options of `svn-url`, `git-local-repo-path`, `rev-timestamp-file` and `revmap-output-file` are required with this option. |   Boolean
|  --svn-url                  |      Svn url that should be used in revmap generation.                                    |   String
|  --git-local-repo-path      |      Local git repo path that should be used in revmap generation.                        |   String
|  --rev-timestamp-file       |      File containing svn revision and timestamps that should be used in revmap generation.|   String
|  --revmap-output-file       |      File to output the generated revmap.                                                 |   String
|  -h, help                   |      Show help about tractive, or you can provide a command to know more about a single command. | --
|  -I, --import-from-file     |      Import issues from a json file.                                                      |   String
|  -i, --info                 |      Reports existing labels and users in the database.                                   |   Boolean
|  -L, --log-file             |      Name of the logfile to output logs.                                                  |   String
|  -M, --mockup               |      Create mocked closed issues on Github for deleted tickets on trac.                   |   Boolean
|  -o, --opened-only          |      Skips the import of closed tickets.                                                  |   Boolean
|  -r, --rev-map-file         |      Allows to specify a commit revision mapping FILE.                                    |   String
|  -S, --single-post          |      Put all issue comments in the first message.                                         |   Boolean
|  -s, --start-at             |      Start migration from ticket with number <ID>.                                        |   String
|  -v, --verbose              |      Verbose mode.                                                                        |   Boolean
|===

=== Getting started

Copy the link:config.example.yaml[example YAML configuration] and adapt it
as needed:

    cp config.example.yaml config.yaml
    vi config.yaml

Thereafter just invoke `tractive`:

    tractive

If this fails with an error, make sure to have a look at the
[Dependencies](#dependencies) section.

By default, `tractive` assumes the file `config.yaml` in the same
directory as the script. You can also specify the configuration file on
the command line:

    tractive -c foo.yaml

Add the `-v` flag for more verbose output:

    tractive -v

Add the `-o` flag to only import the tickets that are not in a `closed`
status:

    tractive -o

To resume the migration at a given Trac ticket ID, use `-s`:

    tractive -s 42

If you want all Trac comments/changes to be compiled into a single post
on the github issue:

    tractive -S

If you migrate to a bare github, you might want want to ensure that the
ticket ids do not change. In this case you can create dummy tickets
for IDs missing in Trac (because they were deleted). The process might
interrupt, so you can still specify the first number to transfer.

    tractive -M -s 601

NOTE: When converting your Trac setup to github, it is prudent to
first try the migration into a test repository which you can delete
afterwards. If this worked out fine and delivered the expected results,
one can still aim the script at the real repository.

=== Issue numbers

By default, tractive will verify that the created issue numbers match
the ticket IDs of the corresponding trac ticket and error-exit if the
number is off.

If you need this behaviour, you should also disable user interactions by
setting **Limit to repository collaborators** under your repository
settings. Alternatively, when migrating issues to a new repository,
import the issues on a test-repository and rename the repository to the
final name when the import went satisfactory.

You can disable this check by using the *fast* option:

    tractive -F

This will also make your import much faster (but after the script has
finished, it can still take some time until the issues are created on
github).

Using this option is obligatory, if you know that the ticket IDs will
not match, e.g. because non-Trac tickets already exist. In this case,
you must also specify the ID of the first ticket to be migrated (even if
it is 1):

    tractive -F -s 1

If you start to import in a fresh github project, tractive can create
dummy tickets issue numbers not available in trac. This even works if
you want to run it multiple times. In this case you need to provide -s
for the first id not available in Github.

    tractive -M

== Details

=== Technology

It uses uses GitHub's new
https://gist.github.com/jonmagic/5282384165e0f86ef105[Issue import API]
to create Issues:

* without hitting abuse detection warnings and getting blocked
* without sending email notifications
* without increasing your contribution count to ridiculous heights
* much faster than with the https://developer.github.com/v3/issues[normal issues API]
* with correct creation/closed date set
* atomically without users being able to interfere in the creation of
  a single issue

=== Configuration

The YAML configuration file contains four sections. The section `trac`
includes all Trac-related configuration options. The database URL
follows the scheme described
http://sequel.jeremyevans.net/rdoc/classes/Sequel.html#method-c-connect[here].

The section `github` includes the repository to migrate as well an API
token which can be generated under
https://github.com/settings/tokens[Settings > Personal Access Tokens].

The section `labels` allows for custom label mappings. Since github's
issue tracker does not have a first-class notion of ticket priority,
type, and version information, tractive supports expressing these in the
form of labels.

The section `users` contains a one-to-one mapping between trac usernames
or email addresses and github usernames for users for which no github
credentials are known or can't be used and are thus not stored in the
`github` section. As soon as you have the login credentials for a user
please use the `github` `logins` section in the config instead.

The section `milestones` contains a mapping of milestones as it is
generated by tractive -i

The section `attachments` specifies how you want to grab attachments. In
particular the `attachment_uri` supports the case that the `imagename` is
embedded in the uri:

The imagename is built of ticket_id and image filename. `exportfolder`
is the folder where the images will be downloaded to on the trac
system.

``` {.yaml}
attachments:
  url: https://abc.com/raw-attachment/ticket
  export_folder: ./attachments
  export_script: attachments.sh
```

You can use

    tractive -i

to produce a yaml file with labels, users, milestones etc. You can copy
this into the config file and adapt it as required.

it also produces a shell script which in invokes `trac-admin` to download
the attachments from trac.

== Development

After checking out the repo, run `bin/setup` to install dependencies. Then, run
`rake spec` to run the tests. You can also run `bin/console` for an interactive
prompt that will allow you to experiment.

To install this gem onto your local machine, run `bundle exec rake install`. To
release a new version, update the version number in `version.rb`, and then run
`bundle exec rake release`, which will create a git tag for the version, push
git commits and the created tag, and push the `.gem` file to
https://rubygems.org[rubygems.org].

== Contributing

Bug reports and pull requests are welcome on GitHub at
https://github.com/ietf-ribose/tractive. This project is intended to be a safe,
welcoming space for collaboration, and contributors are expected to adhere to
the
https://github.com/ietf-ribose/tractive/blob/main/CODE_OF_CONDUCT.md[code of conduct].

== Code of Conduct

Everyone interacting in the Tractive project's codebases, issue trackers, chat
rooms and mailing lists is expected to follow the
https://github.com/ietf-ribose/tractive/blob/main/CODE_OF_CONDUCT.md[code of conduct].

== License

Tractive and its supporting code (from trac-hub) are licensed under a
link:LICENSE.md[BSD-style licence].

Tractive is funded and developed by https://github.com/riboseinc[Ribose Inc.]
