trac:
  database: sqlite://db/trac-test.db
  # database: mysql2://user:password@host:port/database
  # database: mysql2://root:password@127.0.0.1:3306/foobar
  # ticketbaseurl: https://foo.bar/trac/foobar/ticket

github:
  repo: 'test/repo'
  token: 'test_token'

revmap_path: "spec/files/revmap_spec.txt"

# make sure not to typo the GitHub username as the issue will fail to create if a ticket's owner (assignee) has a valid mapping below
users:
  henrik@levkowetz.com:
    email: henrik@levkowetz.com
    name: henrik
    username: henrik@levkowetz.com

  fenner@research.att.com:
    email: fenner@research.att.com
    name:
    username: fenner@research.att.com

  barbara.fuller@neustar.biz:
    email: barbara.fuller@neustar.biz
    name: Barbara Fuller
    username: barbara.fuller@neustar.biz

  presnick@qualcomm.com:
    email: presnick@qualcomm.com
    name:
    username: presnick@qualcomm.com

  smccammon@amsl.com:
    email: smccammon@amsl.com
    name:
    username: smccammon@amsl.com

  presnick@qti.qualcomm.com:
    email: presnick@qti.qualcomm.com
    name:
    username: presnick@qti.qualcomm.com

  martin.thomson@gmail.com:
    email: martin.thomson@gmail.com
    name:
    username: martin.thomson@gmail.com

  rcross@amsl.com:
    email: rcross@amsl.com
    name:
    username: rcross@amsl.com

  cmorgan@amsl.com:
    email: cmorgan@amsl.com
    name:
    username: cmorgan@amsl.com

  valery@smyslov.net:
    email: valery@smyslov.net
    name:
    username: valery@smyslov.net

  rjsparks@nostrum.com:
    email: rjsparks@nostrum.com
    name:
    username: rjsparks@nostrum.com

  michael.lee@neustar.biz:
    email: michael.lee@neustar.biz
    name:
    username: michael.lee@neustar.biz

  '':
    email: ''
    name:
    username:

  jennifer@painless-security.com:
    email: jennifer@painless-security.com
    name:
    username: jennifer@painless-security.com

  pasi.eronen@nokia.com:
    email: pasi.eronen@nokia.com
    name:
    username: pasi.eronen@nokia.com

  adam@nostrum.com:
    email: adam@nostrum.com
    name:
    username: adam@nostrum.com

  mcr@sandelman.ca:
    email: mcr@sandelman.ca
    name:
    username: mcr@sandelman.ca

  jmh@joelhalpern.com:
    email: jmh@joelhalpern.com
    name:
    username: jmh@joelhalpern.com

  mark@painless-security.com:
    email: mark@painless-security.com
    name:
    username: mark@painless-security.com

  vidyut.luther@neustar.biz:
    email: vidyut.luther@neustar.biz
    name:
    username: vidyut.luther@neustar.biz

  comimom@gmail.com:
    email: comimom@gmail.com
    name:
    username: comimom@gmail.com

  nathan@resolutehosting.com:
    email: nathan@resolutehosting.com
    name:
    username: nathan@resolutehosting.com

  spikeekips@gmail.com:
    email: spikeekips@gmail.com
    name:
    username: spikeekips@gmail.com

  ekr@rtfm.com:
    email: ekr@rtfm.com
    name:
    username: ekr@rtfm.com

  fluffy@cisco.com:
    email: fluffy@cisco.com
    name:
    username: fluffy@cisco.com

  rjs@nostrum.com:
    email: rjs@nostrum.com
    name:
    username: rjs@nostrum.com

  lars.eggert@nokia.com:
    email: lars.eggert@nokia.com
    name:
    username: lars.eggert@nokia.com

  fenner@fenron.com:
    email: fenner@fenron.com
    name:
    username: fenner@fenron.com

  chris.newman@sun.com:
    email: chris.newman@sun.com
    name:
    username: chris.newman@sun.com

  cabo@tzi.org:
    email: cabo@tzi.org
    name:
    username: cabo@tzi.org

  jelte@nlnetlabs.nl:
    email: jelte@nlnetlabs.nl
    name:
    username: jelte@nlnetlabs.nl

  arifumi@nttv6.net:
    email: arifumi@nttv6.net
    name:
    username: arifumi@nttv6.net

  ben@nostrum.com:
    email: ben@nostrum.com
    name:
    username: ben@nostrum.com

  tony@att.com:
    email: tony@att.com
    name:
    username: tony@att.com

  kivinen@iki.fi:
    email: kivinen@iki.fi
    name:
    username: kivinen@iki.fi

  suresh.krishnan@ericsson.com:
    email: suresh.krishnan@ericsson.com
    name:
    username: suresh.krishnan@ericsson.com

  matthijs@nlnetlabs.nl:
    email: matthijs@nlnetlabs.nl
    name:
    username: matthijs@nlnetlabs.nl

  olau@iola.dk:
    email: olau@iola.dk
    name:
    username: olau@iola.dk

  esanchez@yaco.es:
    email: esanchez@yaco.es
    name:
    username: esanchez@yaco.es

  wiggins@concentricsky.com:
    email: wiggins@concentricsky.com
    name:
    username: wiggins@concentricsky.com

  peter.musgrave@magorcorp.com:
    email: peter.musgrave@magorcorp.com
    name:
    username: peter.musgrave@magorcorp.com

  fenner@fenron.net:
    email: fenner@fenron.net
    name:
    username: fenner@fenron.net

  azarubin@yaco.es:
    email: azarubin@yaco.es
    name:
    username: azarubin@yaco.es

  jtarragon@yaco.es:
    email: jtarragon@yaco.es
    name:
    username: jtarragon@yaco.es

  bmheight@gmail.com:
    email: bmheight@gmail.com
    name:
    username: bmheight@gmail.com

  shane@time-travellers.org:
    email: shane@time-travellers.org
    name:
    username: shane@time-travellers.org

  martin@iola.dk:
    email: martin@iola.dk
    name:
    username: martin@iola.dk

  york@isoc.org:
    email: york@isoc.org
    name:
    username: york@isoc.org

  housley@vigilsec.com:
    email: housley@vigilsec.com
    name:
    username: housley@vigilsec.com

  rbarnes@bbn.com:
    email: rbarnes@bbn.com
    name:
    username: rbarnes@bbn.com

  ejimenez@yaco.es:
    email: ejimenez@yaco.es
    name:
    username: ejimenez@yaco.es

  ietf@augustcellars.com:
    email: ietf@augustcellars.com
    name:
    username: ietf@augustcellars.com

  lars@netapp.com:
    email: lars@netapp.com
    name:
    username: lars@netapp.com

  markus.stenberg@iki.fi:
    email: markus.stenberg@iki.fi
    name:
    username: markus.stenberg@iki.fi

  tterriberry@mozilla.com:
    email: tterriberry@mozilla.com
    name:
    username: tterriberry@mozilla.com

  bartosz.balazinski@interdigital.com:
    email: bartosz.balazinski@interdigital.com
    name:
    username: bartosz.balazinski@interdigital.com

  liudapeng@chinamobile.com:
    email: liudapeng@chinamobile.com
    name:
    username: liudapeng@chinamobile.com

  fanpeng@chinamobile.com:
    email: fanpeng@chinamobile.com
    name:
    username: fanpeng@chinamobile.com

  gnocuil@gmail.com:
    email: gnocuil@gmail.com
    name:
    username: gnocuil@gmail.com

  denghui@chinamobile.com:
    email: denghui@chinamobile.com
    name:
    username: denghui@chinamobile.com

  sunqi.csnet.thu@gmail.com:
    email: sunqi.csnet.thu@gmail.com
    name:
    username: sunqi.csnet.thu@gmail.com

  phdgang@gmail.com:
    email: phdgang@gmail.com
    name:
    username: phdgang@gmail.com

  harald@alvestrand.no:
    email: harald@alvestrand.no
    name:
    username: harald@alvestrand.no

  denglingli@chinamobile.com:
    email: denglingli@chinamobile.com
    name:
    username: denglingli@chinamobile.com

  buildbot@tools.ietf.org:
    email: buildbot@tools.ietf.org
    name:
    username: buildbot@tools.ietf.org

  willem@nlnetlabs.nl:
    email: willem@nlnetlabs.nl
    name:
    username: willem@nlnetlabs.nl

  tjw.ietf@gmail.com:
    email: tjw.ietf@gmail.com
    name:
    username: tjw.ietf@gmail.com

  stephen.farrell@cs.tcd.ie:
    email: stephen.farrell@cs.tcd.ie
    name:
    username: stephen.farrell@cs.tcd.ie

  mdouglass@sphericalcowgroup.com:
    email: mdouglass@sphericalcowgroup.com
    name:
    username: mdouglass@sphericalcowgroup.com

  anurag_nc@yahoo.com:
    email: anurag_nc@yahoo.com
    name:
    username: anurag_nc@yahoo.com

  mahoney@nostrum.com:
    email: mahoney@nostrum.com
    name:
    username: mahoney@nostrum.com

  peter@akayla.com:
    email: peter@akayla.com
    name:
    username: peter@akayla.com

  sbirkholz@amsl.com:
    email: sbirkholz@amsl.com
    name:
    username: sbirkholz@amsl.com

  david.i.allan@ericsson.com:
    email: david.i.allan@ericsson.com
    name:
    username: david.i.allan@ericsson.com

  alireza.mohammadi@icann.org:
    email: alireza.mohammadi@icann.org
    name:
    username: alireza.mohammadi@icann.org

  suresh@kaloom.com:
    email: suresh@kaloom.com
    name:
    username: suresh@kaloom.com

  ford@isoc.org:
    email: ford@isoc.org
    name:
    username: ford@isoc.org

  fenton@bluepopcorn.net:
    email: fenton@bluepopcorn.net
    name:
    username: fenton@bluepopcorn.net

  johnl@taugh.com:
    email: johnl@taugh.com
    name:
    username: johnl@taugh.com

  magnus.westerlund@ericsson.com:
    email: magnus.westerlund@ericsson.com
    name:
    username: magnus.westerlund@ericsson.com

  pusateri@bangj.com:
    email: pusateri@bangj.com
    name:
    username: pusateri@bangj.com

  sasha@dashcare.nl:
    email: sasha@dashcare.nl
    name:
    username: sasha@dashcare.nl

  mrcullen42@gmail.com:
    email: mrcullen42@gmail.com
    name:
    username: mrcullen42@gmail.com

  rcross:
    email: rcross
    name:
    username: rcross

  henrik:
    email: henrik
    name:
    username: henrik

  krathnayake@ietf.org:
    email: krathnayake@ietf.org
    name:
    username: krathnayake@ietf.org

  lars@eggert.org:
    email: lars@eggert.org
    name:
    username: lars@eggert.org

  paul.higgs@ericsson.com:
    email: paul.higgs@ericsson.com
    name:
    username: paul.higgs@ericsson.com

  bclaise@cisco.com:
    email: bclaise@cisco.com
    name:
    username: bclaise@cisco.com

  randy@psg.com:
    email: randy@psg.com
    name:
    username: randy@psg.com

  bortzmeyer+ietf@nic.fr:
    email: bortzmeyer+ietf@nic.fr
    name:
    username: bortzmeyer+ietf@nic.fr

  stbryant@cisco.com:
    email: stbryant@cisco.com
    name:
    username: stbryant@cisco.com

  worley@alum.mit.edu:
    email: worley@alum.mit.edu
    name:
    username: worley@alum.mit.edu

  daniele.ceccarelli@ericsson.com:
    email: daniele.ceccarelli@ericsson.com
    name:
    username: daniele.ceccarelli@ericsson.com

  acmorton@att.com:
    email: acmorton@att.com
    name:
    username: acmorton@att.com

  julian.reschke@gmx.de:
    email: julian.reschke@gmx.de
    name:
    username: julian.reschke@gmx.de

  paul.hoffman@vpnc.org:
    email: paul.hoffman@vpnc.org
    name:
    username: paul.hoffman@vpnc.org

  brian@innovationslab.net:
    email: brian@innovationslab.net
    name:
    username: brian@innovationslab.net

  mnot@pobox.com:
    email: mnot@pobox.com
    name:
    username: mnot@pobox.com

  davemgarrett@gmail.com:
    email: davemgarrett@gmail.com
    name:
    username: davemgarrett@gmail.com

  turners@ieca.com:
    email: turners@ieca.com
    name:
    username: turners@ieca.com

  chopps@rawdofmt.org:
    email: chopps@rawdofmt.org
    name:
    username: chopps@rawdofmt.org

  jonathan@vidyo.com:
    email: jonathan@vidyo.com
    name:
    username: jonathan@vidyo.com

  cbowers@juniper.net:
    email: cbowers@juniper.net
    name:
    username: cbowers@juniper.net

  lloyd.wood@yahoo.co.uk:
    email: lloyd.wood@yahoo.co.uk
    name:
    username: lloyd.wood@yahoo.co.uk

  adityachunar12345@gmail.com:
    email: adityachunar12345@gmail.com
    name:
    username: adityachunar12345@gmail.com

  adrian@olddog.co.uk:
    email: adrian@olddog.co.uk
    name:
    username: adrian@olddog.co.uk

  paul@nohats.ca:
    email: paul@nohats.ca
    name:
    username: paul@nohats.ca

  vkg@bell-labs.com:
    email: vkg@bell-labs.com
    name:
    username: vkg@bell-labs.com

  jclarke@cisco.com:
    email: jclarke@cisco.com
    name:
    username: jclarke@cisco.com

  mdb@juniper.net:
    email: mdb@juniper.net
    name:
    username: mdb@juniper.net

  nishida@sfc.wide.ad.jp:
    email: nishida@sfc.wide.ad.jp
    name:
    username: nishida@sfc.wide.ad.jp

  jbui@amsl.com:
    email: jbui@amsl.com
    name:
    username: jbui@amsl.com

  serge.raes@orange.com:
    email: serge.raes@orange.com
    name:
    username: serge.raes@orange.com

  johnl@iecc.com:
    email: johnl@iecc.com
    name:
    username: johnl@iecc.com

  rg+ietf@qti.qualcomm.com:
    email: rg+ietf@qti.qualcomm.com
    name:
    username: rg+ietf@qti.qualcomm.com

  watsonbladd@gmail.com:
    email: watsonbladd@gmail.com
    name:
    username: watsonbladd@gmail.com

  gregimirsky@gmail.com:
    email: gregimirsky@gmail.com
    name:
    username: gregimirsky@gmail.com

  jmagallanes@amsl.com:
    email: jmagallanes@amsl.com
    name:
    username: jmagallanes@amsl.com

  dhruv.ietf@gmail.com:
    email: dhruv.ietf@gmail.com
    name:
    username: dhruv.ietf@gmail.com

  ghwood@ietf.org:
    email: ghwood@ietf.org
    name:
    username: ghwood@ietf.org

  lear@cisco.com:
    email: lear@cisco.com
    name:
    username: lear@cisco.com

  spencerdawkins.ietf@gmail.com:
    email: spencerdawkins.ietf@gmail.com
    name:
    username: spencerdawkins.ietf@gmail.com

  dkg@fifthhorseman.net:
    email: dkg@fifthhorseman.net
    name:
    username: dkg@fifthhorseman.net

milestones:
  Cleanup:
    :name: Cleanup
    :due: 0
    :completed: 0
    :description: ''
  Soonish:
    :name: Soonish
    :due: 1214863200000000
    :completed: 1214863200000000
    :description: ''
  Database Schema Conversion:
    :name: Database Schema Conversion
    :due: 0
    :completed: 1394028718000000
    :description: ''
  Agenda - future:
    :name: Agenda - future
    :due: 0
    :completed: 0
    :description: ''
  5.y.y:
    :name: 5.y.y
    :due: 0
    :completed: 1428660000000000
    :description: ''
  "(None)":
    :name: "(None)"
    :due: 0
    :completed: 0
    :description: ''
labels:
  type:
    task: type_task
    cleanup: type_cleanup
    defect: type_defect
    enhancement: type_enhancement
  component:
    admin/:
      name: 'component: admin/'
      color:
    'Datatracker: Base templates':
      name: 'component: Datatracker: Base templates'
      color:
    'Datatracker: Testing':
      name: 'component: Datatracker: Testing'
      color:
    idtracker/:
      name: 'component: idtracker/'
      color:
    doc/:
      name: 'component: doc/'
      color:
    'Project: Agenda':
      name: 'component: Project: Agenda'
      color:
    doc/charter-:
      name: 'component: doc/charter-'
      color:
    submit/:
      name: 'component: submit/'
      color:
    'MailArchive: User Interface':
      name: 'component: MailArchive: User Interface'
      color:
    group/:
      name: 'component: group/'
      color:
    meeting/:
      name: 'component: meeting/'
      color:
    meeting/*/schedule/:
      name: 'component: meeting/*/schedule/'
      color:
  resolution:
    fixed: resolution_fixed
    wontfix: resolution_wontfix
    overtaken by events: resolution_overtaken by events
    deployed: resolution_deployed
  severity: {}
  priority:
    n/a:
      name: n/a
      color:
    medium:
      name: medium
      color:
    major:
      name: major
      color:
    minor:
      name: minor
      color:
  tracstate:
    accepted:
      name: accepted
      color:
    closed:
      name: closed
      color:

ticket:
  attachments:
    url: http://www.abc.com/test/ticket
    hashed: true

wiki:
  attachments:
    url: http://www.abc.com/test/wiki
    hashed: true
