name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      image: mysql:5.7
      restart: unless-stopped
      env:
        - MYSQL_ROOT_PASSWORD=password
      ports:
        - 3306:3306
      options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: Run the default task
      run: |
        gem install bundler -v 2.2.15
        bundle install
        bundle exec rake
